# Usamos una imagen ligera de Nginx
FROM nginx:alpine

# Copiamos los archivos HTML/JS al directorio público de Nginx
COPY . /usr/share/nginx/html

# Exponemos el puerto 80 (el estándar para webs)
EXPOSE 80